export const builtInFontFamilies: string[] = [
  "SimSun",
  "SimHei",
  "Microsoft Yahei",
  "Microsoft JhengHei",
  "KaiTi",
  "NSimSun",
  "FangSong",
  "PingFang SC",
  "STHeiti",
  "STKaiti",
  "STSong",
  "STFangsong",
  "STZhongsong",
  "STHupo",
  "STXinwei",
  "STLiti",
  "STXingkai",
  "Hiragino Sans GB",
  "Lantinghei SC",
  "Hanzipen SC",
  "Hannotate SC",
  "Songti SC",
  "Wawati SC",
  "Weibei SC",
  "Xingkai SC",
  "Yapi SC",
  "Yuanti SC",
  "YouYuan",
  "LiSu",
  "STXihei",
  "STKaiti",
  "STSong",
  "STFangsong",
  "STZhongsong",
  "STCaiyun",
  "STHupo",
  "STXinwei",
  "STLiti",
  "STXingkai",
  "FZShuTi",
  "FZYaoti",
]
export const builtInFontNames: { [key in string]?: string } = {
  "SimSun": "宋体",
  "SimHei": "黑体",
  "Microsoft Yahei": "微软雅黑",
  "Microsoft JhengHei": "微软正黑体",
  "KaiTi": "楷体",
  "NSimSun": "新宋体",
  "FangSong": "仿宋",
  "PingFang SC": "苹方",
  "STHeiti": "华文黑体",
  "STKaiti": "华文楷体",
  "STSong": "华文宋体",
  "STFangsong": "华文仿宋",
  "STZhongsong": "华文中宋",
  "STHupo": "华文琥珀",
  "STXinwei": "华文新魏",
  "STLiti": "华文隶书",
  "STXingkai": "华文行楷",
  "Hiragino Sans GB": "冬青黑体简",
  "Lantinghei SC": "兰亭黑-简",
  "Hanzipen SC": "翩翩体-简",
  "Hannotate SC": "手札体-简",
  "Songti SC": "宋体-简",
  "Wawati SC": "娃娃体-简",
  "Weibei SC": "魏碑-简",
  "Xingkai SC": "行楷-简",
  "Yapi SC": "雅痞-简",
  "Yuanti SC": "圆体-简",
  "YouYuan": "幼圆",
  "LiSu": "隶书",
  "STXihei": "华文细黑",
  "STCaiyun": "华文彩云",
  "FZShuTi": "方正舒体",
  "FZYaoti": "方正姚体"
}