export type Setter<T = any> = (v: T) => T;
export type ValueOrSetter<T = any> = T | ((v: T) => T);
export declare function getValue<T = any>(v: ValueOrSetter<T>, prev: T): T;
export * from "./Array";
export * from "./BinaryRange";
export * from "./BinaryTree";
export * from "./Dot";
export * from "./ITree";
export * from "./QuadTree";
export * from "./Rect";
export * from "./Vector";
