import { BaseEvent, Emitter, EventMap, ICallback, IEmitter, IObserver, Listener } from "../event";
import { IFactory, IShapesMgr } from "../mgr";
import { Shape, ShapeData } from "../shape/base";
import { ITool, ToolType } from "../tools";
import { IDot, IRect } from "../utils";
import { ILayer, ILayerInits } from "./Layer";
export interface WhiteBoardOptions {
    layers: ILayerInits[];
    width?: number;
    height?: number;
    toolType?: ToolType;
}
export interface IPointerEventHandler {
    (ev: PointerEvent): void;
}
export declare class WhiteBoard implements IObserver, IEmitter, IShapesMgr {
    private _factory;
    private _toolType;
    private _layers;
    private _currentLayer?;
    private _layerMap;
    private _shapesMgr;
    private _mousedown;
    private _tools;
    private _tool;
    private _selects;
    private _eventsObserver;
    private _eventEmitter;
    private _operator;
    get width(): number;
    set width(v: number);
    get height(): number;
    set height(v: number);
    layer(idx: number): ILayer;
    setCurrentLayer(idx: number): boolean;
    constructor(factory: IFactory, options: WhiteBoardOptions);
    finds(ids: string[]): Shape[];
    find(id: string): Shape | undefined;
    toJson(): any;
    toJsonStr(): string;
    fromJson(jobj: any): void;
    fromJsonStr(json: string): void;
    shapes(): Shape<ShapeData>[];
    exists(...items: Shape<ShapeData>[]): number;
    hit(rect: IRect): Shape<ShapeData> | undefined;
    hits(rect: IRect): Shape<ShapeData>[];
    addEventListener<K extends keyof EventMap>(type: K, callback: (e: EventMap[K]) => any): Listener;
    removeEventListener<K extends keyof EventMap>(type: K, callback: (e: EventMap[K]) => any): void;
    dispatchEvent(e: BaseEvent): void;
    on<K extends keyof EventMap>(type: K, callback: (evt: EventMap[K]) => any): () => void;
    once<K extends keyof EventMap>(type: K, callback: (evt: EventMap[K]) => any): () => void;
    emit(e: BaseEvent): void;
    listenTo<K extends keyof GlobalEventHandlersEventMap>(target: EventTarget, type: K, callback: (e: GlobalEventHandlersEventMap[K]) => any): () => void;
    listenTo(target: EventTarget, type: string, callback: (e: Event) => void): () => void;
    listenTo(target: Emitter, type: string, callback: ICallback): () => void;
    listenTo(target: Emitter | EventTarget, type: string, callback: ICallback | ((e: Event) => void)): () => void;
    destory(): void;
    get factory(): IFactory;
    set factory(v: IFactory);
    currentLayer(): ILayer;
    ctx(idx?: number): CanvasRenderingContext2D | null | undefined;
    octx(idx?: number): CanvasRenderingContext2D | null | undefined;
    onscreen(idx?: number): HTMLCanvasElement | undefined;
    offscreen(idx?: number): HTMLCanvasElement | undefined;
    get toolType(): string;
    set toolType(v: string);
    setToolType(to: ToolType): void;
    get selects(): Shape<ShapeData>[];
    set selects(v: Shape<ShapeData>[]);
    add(...shapes: Shape[]): number;
    remove(...shapes: Shape[]): number;
    removeAll(): number;
    removeSelected(): void;
    selectAll(): void;
    deselect(): void;
    selectAt(rect: IRect): Shape[];
    selectNear(rect: IRect): Shape | undefined;
    getDot(ev: MouseEvent | PointerEvent): IDot;
    get tools(): {
        [x: string]: ITool | undefined;
    };
    get tool(): ITool;
    pointerdown: IPointerEventHandler;
    pointermove: IPointerEventHandler;
    pointerup: IPointerEventHandler;
    private _dirty;
    markDirty(rect: IRect): void;
    render(): void;
}
